name: Refresh JSON from Apps Script

on:
  schedule:
    - cron: "*/5 * * * *"   # fastest allowed on GitHub
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: refresh-json
  cancel-in-progress: true   # ensure no overlap; new run cancels old if still running

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 6       # 4m45s loop + network/commit time buffer

    steps:
      - uses: actions/checkout@v4

      - name: Fetch and update every 15s (~4m45s total)
        run: |
          set -euo pipefail
          for i in $(seq 1 19); do
            echo "---- Iteration $i ----"
            TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            # Fetch (cache-busted) with light retries
            URL="https://script.googleusercontent.com/macros/echo?user_content_key=AehSKLhh1r78JrUd93cX26iZRlkTw-VXjIgZwmVlrbvLcgk0i8AcCewmsoa3IWK8eB-_E3tiYv4UnPLHmD_D438n0kXSCU6UUOvkyU6d1lz09ch9hSQ9rcVYFKRF7fsNRtA-Whh5JQ-algrla2A-1f-zDlIcbGUUq4QbGAfVIUTdTTtG2etKFWzuiqgi2vI49NCvHnsAxmIkD77-mPeo8sNWYvFIhkGoHaep9UWELf9Ki3dnn0wJsGiigJHj9klDtRb16QAnrqGIx3mbFuW3jj1NN1-cxtlkhA&lib
