name: Refresh JSON from Apps Script

on:
  schedule:
    - cron: "*/5 * * * *"   # fastest allowed
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: refresh-json
  cancel-in-progress: false   # don't cancel the previous loop mid-run

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 7        # job must outlive the loop
    steps:
      - uses: actions/checkout@v4

      - name: Run minutely for ~6 minutes
        run: |
          set -euo pipefail
          for i in $(seq 1 6); do
            echo "Iteration $i"

            # Fetch upstream JSON
            curl -fsSL "https://script.googleusercontent.com/macros/echo?user_content_key=...&lib=..." -o new.json
            if command -v jq >/dev/null 2>&1; then jq . new.json > new.pretty.json && mv new.pretty.json new.json; fi

            # Replace if changed
            if [ ! -f data.json ] || ! cmp -s new.json data.json; then
              mv new.json data.json
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add data.json
              git commit -m "chore: refresh data.json [skip ci]" || true
              git push || true
              echo "Committed an update."
            else
              echo "No change."
            fi

            # Sleep until next minute unless it's the last iteration
            if [ "$i" -lt 6 ]; then sleep 60; fi
          done
