name: Refresh JSON from Apps Script

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch: {}      # allow manual runs

permissions:
  contents: write

concurrency:
  group: refresh-json
  cancel-in-progress: true   # cancel any older run still looping

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 6       # ~5 min loop + buffer

    steps:
      - uses: actions/checkout@v4

      - name: Fetch and update every 15s (~4m45s total)
        run: |
          set -euo pipefail

          for i in $(seq 1 19); do
            echo "---- Iteration $i ----"
            TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            URL="https://script.googleusercontent.com/macros/echo?user_content_key=AehSKLhh1r78JrUd93cX26iZRlkTw-VXjIgZwmVlrbvLcgk0i8AcCewmsoa3IWK8eB-_E3tiYv4UnPLHmD_D438n0kXSCU6UUOvkyU6d1lz09ch9hSQ9rcVYFKRF7fsNRtA-Whh5JQ-algrla2A-1f-zDlIcbGUUq4QbGAfVIUTdTTtG2etKFWzuiqgi2vI49NCvHnsAxmIkD77-mPeo8sNWYvFIhkGoHaep9UWELf9Ki3dnn0wJsGiigJHj9klDtRb16QAnrqGIx3mbFuW3jj1NN1-cxtlkhA&lib=MqWI2eNabQZJZJ4CRdba0s_OWijhebUwr&t=$TS"

            # Run curl safely — never fail entire job if this fails
            if ! curl -fsSL -L --max-time 15 --retry 2 --retry-delay 1 "$URL" -o new.json; then
              echo "⚠️  curl failed on iteration $i — skipping this tick"
              sleep 15
              continue
            fi

            # Optional: prettify for cleaner diffs
            if command -v jq >/dev/null 2>&1; then
              jq . new.json > new.pretty.json && mv new.pretty.json new.json
            fi

            # Replace if changed
            if [ ! -f data.json ]; then
              cp new.json data.json
              echo "Created data.json (first run)"
            elif ! cmp -s new.json data.json; then
              mv new.json data.json
              echo "Updated data.json"
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add data.json
              git commit -m "chore: refresh data.json (tick $i) [skip ci]" || true
              git push || true
            else
              echo "No change."
              rm -f new.json
            fi

            # Sleep ~15 seconds (plus tiny random jitter)
            if [ "$i" -lt 19 ]; then
              J=$((RANDOM % 3))
              sleep $((15 + J))
            fi
          done
